from discord import Embed, File
from discord.ext import commands

import perms

class Manual(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(cls=perms.Lock, name='ids', aliases=[], usage='ids')
    async def ids(self, ctx):
        desc = ('Discord allows users to obtain IDs through the user interface. '
                'Users, servers, channels, messages, roles, etc. all have a unique ID '
                'generated by Discord. They are stored as a 64-bit unsigned integer.\n\n'
                'To obtain an ID from an object in Discord, you must enable developer '
                'mode. Go to User Settings > Appearance > Advanced and toggle on '
                '"Developer Mode." By right clicking any user, server, etc. '
                'there is now a "Copy ID" item in the context menu.')
        embed = Embed(description=desc.replace(' '*8, ''))
        embed.set_image(url='attachment://unknown.png')

        await ctx.send(file=File('assets/devmode.png', 'unknown.png'), embed=embed)

    @commands.command(cls=perms.Lock, name='moderation', aliases=[], usage='moderation')
    async def moderation(self, ctx):
        desc = ('Moderators are intended to have three key powers: deleting messages, '
                'muting, and detaining. Mods are purposefully not given the permission '
                'to ban members by themselves, otherwise it could lead to overzealous'
                'mods. Accordingly, instead mods are given the `detain` command where'
                'the member in question is locked in a private channel and they may '
                'appeal their case while staff members vote on whether or not to ban '
                'the member. The member is only banned through a majority vote among '
                'the moderators.\n\nShown below is an example screenshot of what a case '
                'might look like.')
        embed = Embed(description=desc.replace(' '*8, ''))
        embed.set_image(url='attachment://unknown.png')

        await ctx.send(file=File('assets/detain.png', 'unknown.png'), embed=embed)

def setup(bot):
    bot.add_cog(Manual(bot))